---
- file: path=/opt/src state=directory
- file: path=/opt/build state=directory
- file: path=/etc/supervisor/conf.d state=directory

- group: name=zookeeper system=yes
- user: name=zookeeper group=zookeeper system=yes

- get_url: url=http://ftp.heanet.ie/mirrors/www.apache.org/dist/zookeeper/zookeeper-{{zookeeper.version}}/zookeeper-{{zookeeper.version}}.tar.gz 
           dest=/opt/src/zookeeper-{{zookeeper.version}}.tar.gz
           sha256sum={{zookeeper.sha256sum}}

- command: chdir=/opt tar xzf /opt/src/zookeeper-{{zookeeper.version}}.tar.gz creates=/opt/zookeeper-{{zookeeper.version}}/bin/zkCli.sh

- template: src=myid dest=/var/lib/zookeeper/myid owner=zookeeper group=zookeeper
  notify:
    - restart zookeeper

- template: src=zoo.cfg dest=/opt/zookeeper-{{zookeeper.version}}/conf/zoo.cfg 
  notify:
    - restart zookeeper

- file: path=/opt/zookeeper-{{zookeeper.version}} state=directory owner=zookeeper group=zookeeper recurse=yes
- file: path=/var/lib/zookeeper state=directory owner=zookeeper group=zookeeper recurse=yes

- template: src=supervisor-zookeeper.conf dest=/etc/supervisor/conf.d/zookeeper.conf
- apt: name=supervisor state=present
- service: name=supervisor enabled=yes state=started

## notes - http://systemsarchitect.net/painless-guide-to-solr-cloud-configuration/
#          https://cwiki.apache.org/confluence/display/solr/Command+Line+Utilities
## bootstrap the solrcloud instance (run the stock start.jar once to get everything unpacked)
# $ ./cloud-scripts/zkcli.sh -cmd upconfig -zkhost 127.0.0.1:2181 -d /opt/solr/dri/collection1/conf -n collection1
# $ ./cloud-scripts/zkcli.sh -cmd linkconfig -zkhost 127.0.0.1:2181 -collection collection1 -confname collection1 -solrhome solr
# $ ./cloud-scripts/zkcli.sh -cmd bootstrap -zkhost 127.0.0.1:2181 -solrhome solr
