---
- file: path=/opt/src state=directory
- file: path=/opt/build state=directory

- get_url: url=http://ftp.heanet.ie/mirrors/www.apache.org/dist/lucene/solr/{{solr.version}}/solr-{{solr.version}}.tgz
           dest=/opt/src/solr-{{solr.version}}.tgz
           sha256sum={{solr.sha256sum}}

- file: path=/opt/solr/dri/lib state=directory owner=tomcat7 group=tomcat7

- command: chdir=/opt/build tar zxf ../src/solr-{{solr.version}}.tgz creates=/opt/build/solr-{{solr.version}}/README.txt

- command: chdir=/opt/build cp solr-{{solr.version}}/dist/solr-{{solr.version}}.war /opt/solr/solr.war creates=/opt/solr/solr.war

- command: chdir=/opt/build rsync -a solr-{{solr.version}}/dist/ /opt/solr/dri/lib/ creates=/opt/solr/dri/lib/solr-core-{{solr.version}}.jar

- command: chdir=/opt/build rsync -a solr-{{solr.version}}/contrib/ /opt/solr/dri/lib/ creates=/opt/solr/dri/lib/velocity/lib/velocity-1.7.jar

- command: chdir=/opt/build rsync -a solr-{{solr.version}}/example/solr/collection1 /opt/solr/dri/ creates=/opt/solr/dri/collection1


- command: chdir=/opt/solr/dri/collection1 cp conf/lang/stopwords_en.txt conf/stopwords_en.txt creates=/opt/solr/dri/collection1/conf/stopwords_en.txt

- command: chdir=/opt/build cp solr-{{solr.version}}/example/resources/log4j.properties /usr/share/tomcat7/lib

## logging libraries - this changed from solr 4.2 and up
- apt: name=unzip state=present
- get_url: url=http://www.slf4j.org/dist/slf4j-{{slf4j.version}}.zip
           dest=/opt/src/slf4j-{{slf4j.version}}.zip
           sha256sum={{slf4j.sha256sum}}
- command: chdir=/opt/build unzip ../src/slf4j-{{slf4j.version}}.zip creates=/opt/build/slf4j-{{slf4j.version}}/pom.xml
- command: chdir=/opt/build/slf4j-{{slf4j.version}} cp slf4j-api-{{slf4j.version}}.jar        /usr/share/tomcat7/lib/ creates=/usr/share/tomcat7/lib//slf4j-api-{{slf4j.version}}.jar
- command: chdir=/opt/build/slf4j-{{slf4j.version}} cp slf4j-jdk14-{{slf4j.version}}.jar      /usr/share/tomcat7/lib/ creates=/usr/share/tomcat7/lib//slf4j-jdk14-{{slf4j.version}}.jar
- command: chdir=/opt/build/slf4j-{{slf4j.version}} cp jcl-over-slf4j-{{slf4j.version}}.jar   /usr/share/tomcat7/lib/ creates=/usr/share/tomcat7/lib//jcl-over-slf4j-{{slf4j.version}}.jar
- command: chdir=/opt/build/slf4j-{{slf4j.version}} cp log4j-over-slf4j-{{slf4j.version}}.jar /usr/share/tomcat7/lib/ creates=/usr/share/tomcat7/lib//log4j-over-slf4j-{{slf4j.version}}.jar

## solr.xml with zookeeper config
- template: src=precise/solr.xml dest=/opt/solr/dri/solr.xml owner=tomcat7 group=tomcat7
#
## set custom schema
- name: Install solr schema (custom hydra/dri one)
  copy: src={{item}} dest=/opt/solr/dri/collection1/conf/schema.xml owner=tomcat7 group=tomcat7
  with_first_found:
    - files:
        - schema-{{host_group}}.xml
        - schema.xml
      paths:
        - ../files

- file: owner=tomcat7 group=tomcat7 path=/opt/solr recurse=yes state=directory

- template: src=precise/solr-deploy.xml dest=/etc/tomcat7/Catalina/localhost/solr.xml owner=tomcat7 group=tomcat7

- service: name=tomcat7 state=started enabled=yes
