---
- file: path=/opt/src state=directory
- file: path=/opt/build state=directory

- get_url: url=http://ftp.heanet.ie/mirrors/www.apache.org/dist/lucene/solr/{{solr.version}}/solr-{{solr.version}}.tgz
           dest=/opt/src/solr-{{solr.version}}.tgz
           sha256sum={{solr.sha256sum}}

- file: path=/opt/solr/dri/lib state=directory owner=tomcat7 group=tomcat7

- command: chdir=/opt/build tar zxf ../src/solr-{{solr.version}}.tgz creates=/opt/build/solr-{{solr.version}}/README.txt

- command: chdir=/opt/build cp solr-{{solr.version}}/dist/solr-{{solr.version}}.war /opt/solr/solr.war creates=/opt/solr/solr.war
  notify:
    - restore ownership of /opt/solr
    - touch solr context and restart

- command: chdir=/opt/build rsync -a solr-{{solr.version}}/dist/ /opt/solr/dri/lib/ creates=/opt/solr/dri/lib/solr-core-{{solr.version}}.jar
  notify:
    - restore ownership of /opt/solr
    - touch solr context and restart

# get contribs into place (lucene related)
- get_url: url=http://objects.dri.ie/public/solr-contrib-{{solr.version}}.tar
           dest=/opt/src/solr-contrib-{{solr.version}}.tar
           sha256sum={{solr.contrib_sha256sum}}
- command: chdir=/opt/solr/dri/lib tar xf /opt/src/solr-contrib-{{solr.version}}.tar creates=icu4j-49.1.jar
  notify:
    - restore ownership of /opt/solr
    - touch solr context and restart

- command: chdir=/opt/build rsync -a solr-{{solr.version}}/example/solr/collection1 /opt/solr/dri/ creates=/opt/solr/dri/collection1
  notify:
    - restore ownership of /opt/solr
    - touch solr context and restart


- command: chdir=/opt/solr/dri/collection1 cp conf/lang/stopwords_en.txt conf/stopwords_en.txt creates=/opt/solr/dri/collection1/conf/stopwords_en.txt
  notify:
    - restore ownership of /opt/solr
    - touch solr context and restart

- command: chdir=/opt/build cp solr-{{solr.version}}/example/resources/log4j.properties /usr/share/tomcat7/lib

## logging libraries - this changed from solr 4.2 and up
- get_url: url=http://objects.dri.ie/public/solr-contrib-logging-{{solr.version}}.tar
           dest=/opt/src/solr-contrib-logging-{{solr.version}}.tar
           sha256sum={{solr.contrib_logging_sha256sum}}
- command: chdir=/usr/share/tomcat7 tar xf /opt/src/solr-contrib-logging-{{solr.version}}.tar creates=/usr/share/tomcat7/lib/slf4j-api-1.6.6.jar
  notify:
    - restore ownership of /opt/solr
    - restart tomcat7

## solr.xml with zookeeper config
- template: src=precise/solr.xml dest=/opt/solr/dri/solr.xml owner=tomcat7 group=tomcat7
  notify:
    - touch solr context and restart
#
## set custom schema
- name: Install solr schema (custom hydra/dri one)
  copy: src={{item}} dest=/opt/solr/dri/collection1/conf/schema.xml owner=tomcat7 group=tomcat7
  with_first_found:
    - files:
        - schema-{{host_group}}.xml
        - schema.xml
      paths:
        - ../files

- template: src=precise/solr-deploy.xml dest=/etc/tomcat7/Catalina/localhost/solr.xml owner=tomcat7 group=tomcat7

- service: name=tomcat7 state=started enabled=yes

- template: src=bootstrap.sh dest=/opt/build/solr-{{solr.version}}/example/bootstrap.sh mode=0711
- debug: msg="Look at and run /opt/build/solr-{{solr.version}}/example/bootstrap.sh to do the initial zookeeper/solr bootstrapping"
