# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::configure("2") do |global_config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  global_config.vm.box = "precise64"
  global_config.vm.box_url = "http://objects.tchpc.tcd.ie/basebox/precise64.box"
  # assumes vagrant-cachier plugin is installed
  global_config.cache.auto_detect = true

  global_config.vm.define(:hydra) do |config|
    config.vm.network :private_network, ip: "10.0.1.200"
    config.vm.hostname = "hydra.localhost"

#    config.vm.provision :ansible do |ansible|
#      # point Vagrant at the location of your playbook you want to run
#      ansible.playbook =  [ "playbooks/setup.yml" ]
#
#      # the Vagrant VM will be put in this host group change this should
#      # match the host group in your playbook you want to test
#      ansible.hosts = [ "hydra" ]
#    end

    config.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id,
        "--name", "hydra VM",
        "--memory", "2048",
        "--natdnsproxy1", "off",
        "--natdnshostresolver1", "off"
      ]
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end
  end

end
