# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-ansible'

Vagrant::Config.run do |global_config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  global_config.vm.box = "sl64-x86_64"
  global_config.vm.box_url = "http://thammuz.tchpc.tcd.ie/mirrors/boxes/scientificlinux-6.4-x86_64-netboot-devops.box"

  global_config.vm.define(:hydra) do |config|
    config.vm.network :hostonly, "192.168.206.110"
    config.vm.host_name = "hydra.localhost"

#    config.vm.provision :ansible do |ansible|
#      # point Vagrant at the location of your playbook you want to run
#      ansible.playbook =  [ "playbooks/setup.yml" ]
#
#      # the Vagrant VM will be put in this host group change this should
#      # match the host group in your playbook you want to test
#      ansible.hosts = [ "hydra" ]
#    end

    config.vm.customize [
      "modifyvm", :id,
      "--name", "hydra VM",
      "--memory", "1024",
      "--natdnsproxy1", "off",
      "--natdnshostresolver1", "off"
    ]
    config.vm.customize ["setextradata", :id,
      "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

end
