#
# the ceph.conf template could be far more clever, this is just a start of the
# automation process, the osd, mon and mds components should all be seperated
# out into fragments then re-assembled
# 
# This playbook is currently ubuntu specific
#
---
- hosts: ceph-ubuntu;kraken-ubuntu
  user: vagrant
  sudo: True

  vars:
    mon_port: 6789
    mon_ip_a: ${ansible_default_ipv4.address}
    mon_fqdn_a: ${ansible_default_ipv4.address}
    mds_fqdn_a: ${ansible_default_ipv4.address}
    osd_fqdn_0: ${ansible_default_ipv4.address}
    osd_fqdn_1: ${ansible_default_ipv4.address}

  vars_files:
    - ../global_vars.yml

  tasks:

  - name: Install the python-software-properties to get apt-add-repository
    action: apt pkg=python-software-properties state=latest update-cache=yes

  - name: Get the public key for ceph repo
    apt_key: url=https://raw.github.com/ceph/ceph/master/keys/release.asc state=present

  - name: Configure the ceph apt repository
    apt_repository: repo='deb http://ceph.com/debian-bobtail/ $(lsb_release -sc) main'

  - name: Install the latest version of ceph
    action: apt pkg=ceph state=latest update-cache=yes

  - name: authorized_keys for root
    authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" state=present
    
  - name: install insecure private key for root
    action: copy src=files/insecure_private_key dest=/root/.ssh/id_rsa owner=root group=root mode=0600

  - name: install insecure config for root
    action: copy src=files/insecure_config dest=/root/.ssh/config owner=root group=root mode=0600

  - name: authorized_keys for vagrant
    authorized_key: user=vagrant key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key" state=present
    
  - name: install insecure private key for vagrant
    action: copy src=files/insecure_private_key dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=0600

  - name: install insecure config for vagrant
    action: copy src=files/insecure_config dest=/home/vagrant/.ssh/config owner=vagrant group=vagrant mode=0600

  - name: install reference ceph.conf
    action: template src=templates/ceph.j2 dest=/etc/ceph/ceph.conf

  - name: create directories for ceph mons and osds
    action: file path=$item state=directory
    with_items:
      - /var/lib/ceph/osd/ceph-0
      - /var/lib/ceph/osd/ceph-1
      - /var/lib/ceph/mon/ceph-a
      - /var/lib/ceph/mds/ceph-a

  - name: Make sure root fs is mounted with correct settings
    mount: name=/ fstype=ext4 opts=errors=remount-ro,user_xattr src=/dev/mapper/precise64-root passno=1 state=mounted

  - name: create the ceph filesystem
    action: command mkcephfs -a -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.keyring chdir=/etc/ceph creates=/etc/ceph/ceph.keyring
    notify:
      - restart ceph

  - name: start ceph with service command
    action: command service ceph -a start

  - name: start ceph and ensure it is enabled
    action: service name=ceph state=started enabled=yes

  - name: register ceph secret key
    action: shell grep key /etc/ceph/ceph.keyring | awk '{print $3}' > /etc/ceph/admin.secret creates=/etc/ceph/admin.secret

  - name: Wait for mon to come up
    wait_for: host=${mon_ip_a} port=${mon_port}

  - name: mount cephfs to /ceph
    mount: name=/ceph src=${mon_ip_a}:${mon_port}:/ opts=noauto,rw,noexec,nodev,noatime,nodiratime,name=admin,secretfile=/etc/ceph/admin.secret fstype=ceph passno=2 state=mounted
    
  handlers:
    - name: restart ceph
      action: service name=ceph state=restarted
