---
- hosts: all
  user: tchpc
  sudo: True

  tasks:
    - authorized_key: user=tchpc key="{{ lookup('file', '~/.ssh/id_rsa.pub' ) }}" state=present

- hosts: all
  sudo: True
  user: tchpc
  accelerate: True

  tasks:
    #- authorized_key: user=tchpc key='$FILE(../private/keys/{{ item }}.pub )' state=present
    - authorized_key: user=tchpc key="{{ lookup('file', '../private/keys/' +  item + '.pub' ) }}" state=present
      with_items:
        - jtang-dsa
        - jtang-rsa
        - jtang-mba
        - skenny
        - kcassidy
        - ptiernan
    - copy: src=files/sudoers.d-root-tchpc dest=/etc/sudoers.d/user-tchpc owner=root group=root mode=0440
    - apt: update_cache=yes cache_valid_time=3600
