# order matters!
---
- hosts: all
  user: root

  roles:
    - etckeeper
    - common

  post_tasks:
    - copy: src=files/sudoers.d-root-ssh-agent dest=/etc/sudoers.d/root-ssh-agent mode=0640

# Mysql - this is needed before fedora-commons and the rails app is setup
- hosts: mysql
  user: root

  roles:
    - mysql

  tasks:
    - name: create db '{{ fedora_db_name }}'
      mysql_db: db={{ fedora_db_name }} state=present

    - name: create user '{{ fedora_db_user }}' with password '{{ fedora_db_pass }}' for '{{ fedora_db_name }}' and grant all priveleges
      mysql_user: state=present name={{ fedora_db_user }} password={{ fedora_db_pass }} priv={{ fedora_db_name }}.*:ALL host={{ groups['fedora'][0] }}

# Fedora-Commons - Preservation and archival repository
- hosts: fedora
  user: root

  roles:
    - tomcat
    - fedora

# SOLR - search engine
- hosts: solr
  user: root

  roles:
    - tomcat
    - solr

# mod_passenger for the systems that will run the rails app or the resque queues
- hosts: passenger
  user: root

  tasks:
    - name: Create $rvm_user
      user: name={{rvm_user}} state=present shell=/bin/bash

    - name: Make sure .ssh directory exists
      file: path=/home/{{rvm_user}}/.ssh state=directory owner={{ rvm_user }} group={{rvm_user}}

    - authorized_key: user={{rvm_user}} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: install insecure ssh config for $rvm_user if proxy_is_set is defined
      template: src=files/insecure_config_proxy dest=/home/{{rvm_user}}/.ssh/config mode=0600 owner={{ rvm_user }} group={{rvm_user}}
      when: proxy_is_set is defined
      tags: passenger

    - template: src=roles/proxy/templates/curlrc.j2 dest=/home/{{rvm_user}}/.curlrc owner={{rvm_user}} group={{rvm_user}}
      when: proxy_is_set is defined

    - template: src=roles/proxy/templates/gemrc.j2 dest=/home/{{rvm_user}}/.gemrc owner={{rvm_user}} group={{rvm_user}}
      when: proxy_is_set is defined

- hosts: passenger
  user: root

  roles:
    - rvm-common
    - rvm-passenger
