# order matters!
---
- hosts: all
  user: vagrant
  sudo: True

  roles:
    - proxy

  tasks:
    - name: install insecure ssh config for root
      template: src=files/insecure_config_proxy dest=~/.ssh/config mode=0600
      sudo: False

- include: playbooks/devel-vagrant.yml
- include: site-base.yml proxy_is_set=True
# deploy your rails app here (you should deploy it on the machines where you deployed passenger)
- include: playbooks/setup-dri_app.yml proxy_is_set=True
