---
- hosts: all
  user: tchpc
  sudo: True

  tasks:
    - authorized_key: user=tchpc key="{{ lookup('file', '~/.ssh/id_rsa.pub' ) }}" state=present
    - group_by: key="{{ansible_distribution_release}}"

- hosts: Carbon
  sudo: True
  user: tchpc
  #accelerate: True

  tasks:
    #- authorized_key: user=tchpc key='$FILE(../private/keys/{{ item }}.pub )' state=present
    - authorized_key: user=tchpc key="{{ lookup('file', '../private/keys/' +  item + '.pub' ) }}" state=present
      with_items:
        - jtang-dsa
        - jtang-rsa
        - jtang-mba
        - skenny
        - kcassidy
        - ptiernan
    - copy: src=files/sudoers.d-root-tchpc dest=/etc/sudoers.d/user-tchpc owner=root group=root mode=0440

- hosts: precise
  sudo: True
  user: tchpc
  #accelerate: True

  tasks:
    #- authorized_key: user=tchpc key='$FILE(../private/keys/{{ item }}.pub )' state=present
    - authorized_key: user=tchpc key="{{ lookup('file', '../private/keys/' +  item + '.pub' ) }}" state=present
      with_items:
        - jtang-dsa
        - jtang-rsa
        - jtang-mba
        - skenny
        - kcassidy
        - ptiernan
    - authorized_key: user=root key="{{ lookup('file', '../private/keys/' +  item + '.pub' ) }}" state=present
      with_items:
        - jtang-dsa
        - jtang-rsa
        - jtang-mba
        - ptiernan
    - copy: src=files/sudoers.d-root-tchpc dest=/etc/sudoers.d/user-tchpc owner=root group=root mode=0440
    - apt: update_cache=yes cache_valid_time=3600

- hosts: passenger
  sudo: True
  user: tchpc
  #accelerate: True

  tasks:
    - copy: src=/srv/infrastructure/private/keys/dri-deploy dest=/home/{{rvm_user}}/.ssh/id_rsa owner={{rvm_user}} group={{rvm_user}} mode=0600
    - copy: src=/srv/infrastructure/private/keys/dri-deploy.pub dest=/home/{{rvm_user}}/.ssh/id_rsa.pub owner={{rvm_user}} group={{rvm_user}} mode=0600

- hosts: nuig_rnag
  sudo: True
  user: tchpc
  #accelerate: True

  tasks:
    - authorized_key: user={{rvm_user}} key="{{ lookup('file', '/srv/infrastructure/private/keys/dri-deploy.pub') }}"
      ignore_errors: True
    - template: src=files/insecure_config_proxy dest=/home/{{rvm_user}}/.ssh/config mode=0600 owner={{rvm_user}} group={{rvm_user}}
      ignore_errors: True
    - authorized_key: user=root key="{{ lookup('file', '/srv/infrastructure/private/keys/dri-deploy.pub') }}"
    - authorized_key: user=tchpc key="{{ lookup('file', '/srv/infrastructure/private/keys/dri-deploy.pub') }}"

- hosts: buildbot
  sudo: True
  user: tchpc
  #accelerate: True

  tasks:
    - template: src=templates/hosts.buildbot dest=/home/{{rvm_user}}/hosts.buildbot owner={{rvm_user}} group={{rvm_user}} mode=0600 
