# order matters!
---
- hosts: all
  user: vagrant
  sudo: True

  roles:
    - etckeeper
    - common

# Fedora-Commons - Preservation and archival repository
- hosts: fedora
  user: vagrant
  sudo: True

  roles:
    - tomcat
    - mysql
    - fedora

# SOLR - search engine
- hosts: solr
  user: vagrant
  sudo: True

  roles:
    - tomcat
    - solr 

# mod_passenger for the systems that will run the rails app or the resque queues
- hosts: passenger
  user: vagrant
  sudo: True

  roles:
    - rvm-common
    - rvm-passenger

- hosts: rails_app
  user: vagrant
  sudo: True

  tasks:
    ## must configure vhosts to look for a rails app deployment to serve out
    - name: configure rails app
      action: template src=$item dest=/etc/httpd/conf.d/rails-app.conf
      first_available_file:
        - ../templates/rails-app-${host_group}.j2
        - ../templates/rails-app.j2
      notify:
        - restart httpd

    ## additional dependancies needed for hydra-head
    - name: create db '{{ db_name }}'
      mysql_db: db={{ db_name }} state=present

    # usernames and passwords should be included from a file outside of this git-repo, for now this is developmental.
    - name: create user '{{ db_user }}' with password '{{ db_pass }}' for '{{ db_name }}' and grant all priveleges
      mysql_user: state=present name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL

    # optional can be commented out, ruby versions are taken from a previous task
#    - name: Run bundle
#      command: bash -lc 'bundle' chdir=/vagrant/nuig-rnag
#
#    - name: generate assets
#      command: bash -lc 'rake RAILS_ENV=production assets:precompile' chdir=/vagrant/nuig-rnag
#
#    - name: load schema
#      command: bash -lc 'rake RAILS_ENV=production db:schema:load' chdir=/vagrant/nuig-rnag
#
#    - name: db migrate
#      command: bash -lc 'rake RAILS_ENV=production db:migrate' chdir=/vagrant/nuig-rnag

  handlers:
    - include: handlers/main.yml
