# order matters!
---
- hosts: all
  user: vagrant
  sudo: True

  roles:
    - etckeeper
    - common

# Fedora-Commons - Preservation and archival repository
- hosts: fedora
  user: vagrant
  sudo: True

  roles:
    - tomcat
    - mysql
    - fedora

# SOLR - search engine
- hosts: solr
  user: vagrant
  sudo: True

  roles:
    - tomcat
    - solr 

# mod_passenger for the systems that will run the rails app or the resque queues
- hosts: passenger
  user: vagrant
  sudo: True

  roles:
    - rvm-common
    - rvm-passenger

# deploy your rails app here (you should deploy it on the machines where you deployed passenger)
- include: playbooks/setup-dri_app.yml
