# order matters!
---
- hosts: all
  user: root

  pre_tasks:
    - yum: name=yum-plugin-fastestmirror state=absent

  roles:
    - etckeeper
    - common

  post_tasks:
    - selinux: state=permissive policy=targeted
    - copy: src=files/sudoers.d-root-ssh-agent dest=/etc/sudoers.d/root-ssh-agent mode=0640

# Fedora-Commons - Preservation and archival repository
- hosts: fedora
  user: root

  roles:
    - tomcat
    - mysql
    - fedora

# SOLR - search engine
- hosts: solr
  user: root

  roles:
    - tomcat
    - solr

# mod_passenger for the systems that will run the rails app or the resque queues
- hosts: passenger
  user: root

  tasks:
    - name: Create $rvm_user
      user: name={{rvm_user}} state=present

    - name: Make sure .ssh directory exists
      file: path=/home/{{rvm_user}}/.ssh state=directory owner={{ rvm_user }} group={{rvm_user}}

    - name: install insecure ssh config for $rvm_user if proxy_is_set is defined
      template: src=files/insecure_config_proxy dest=~/.ssh/config mode=0600
      sudo_user: $rvm_user
      sudo: True
      when: proxy_is_set is defined

- hosts: passenger
  user: root

  roles:
    - rvm-common
    - rvm-passenger

# deploy your rails app here (you should deploy it on the machines where you deployed passenger)
- include: playbooks/setup-dri_app.yml
