# order matters!
---
- hosts: all
  user: vagrant
  sudo: True

  roles:
    - role: proxy
      proxy_server: proxy.tchpc.tcd.ie
      proxy_port: 8080
      socks_server: 134.226.112.43
      socks_port: 1080
    - etckeeper
    - common

  tasks:
    - name: /root/.pip
      file: path=/root/.pip/ owner=root  mode=0755 state=directory

    - name: write /root/.pip/pip.conf
      action: template src=templates/pip.j2 dest=/root/.pip/pip.conf owner=root
      tags: configuration

    - name: install insecure ssh config for root
      template: src=files/insecure_config_proxy dest=~/.ssh/config mode=0600
      sudo: False



- hosts: fedora
  user: vagrant
  sudo: True

  roles:
    - tomcat
    - role: mysql
      mysql_root_password: CHANGEME

  tasks:
    - name: create db '{{ fedora_db_name }}'
      action: mysql_db db={{ fedora_db_name }} state=present

    - name: create user '{{ fedora_db_user }}' with password '{{ fedora_db_pass }}' for '{{ fedora_db_name }}' and grant all priveleges
      action: mysql_user state=present name={{ fedora_db_user }} password={{ fedora_db_pass }} priv={{ fedora_db_name }}.*:ALL

    - include: tasks/fedora-sl.yml

- hosts: hydra
  user: vagrant
  sudo: True

  roles:
    - role: rvm-common
      rvm_user: vagrant
      ruby_version: 2.0.0-p195
      rvm_home: /home/${rvm_user}/.rvm
      rvm_bindir: ${rvm_home}/bin
    - role: rvm-passenger
      rvm_user: vagrant
      ruby_version: 2.0.0-p195
      rvm_home: /home/${rvm_user}/.rvm
      rvm_bindir: ${rvm_home}/bin
    - redis
    - role: mysql
      mysql_root_password: CHANGEME

  tasks:
    ## must configure vhosts to look for a rails app deployment to serve out
 #  - name: configure rails app
 #    action: template src=$item dest=/etc/httpd/conf.d/rails-app.conf
 #    first_available_file:
 #      - ../templates/rails-app-${host_group}.j2
 #      - ../templates/rails-app.j2
 #    notify:
 #      - restart httpd 

    ## additional dependancies needed for hydra-head
    - name: create db '{{ db_name }}'
      action: mysql_db db={{ db_name }} state=present

    # usernames and passwords should be included from a file outside of this git-repo, for now this is developmental.
    - name: create user '{{ db_user }}' with password '{{ db_pass }}' for '{{ db_name }}' and grant all priveleges
      action: mysql_user state=present name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL

    - include: tasks/solr-sl.yml

    # optional can be commented out, ruby versions are taken from a previous task
#    - name: Run bundle
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && bundle chdir=/vagrant/nuig-rnag
#
#    - name: generate assets
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production assets:precompile chdir=/vagrant/nuig-rnag
#
#    - name: load schema
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production db:schema:load chdir=/vagrant/nuig-rnag
#
#    - name: db migrate
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production db:migrat chdir=/vagrant/nuig-rnag

  handlers:
    - include: handlers/main.yml
