# order matters!
---
- hosts: all
  user: root

  roles:
    - proxy

  tasks:
    - name: /root/.pip
      file: path=/root/.pip/ owner=root  mode=0755 state=directory

    - name: write /root/.pip/pip.conf
      action: template src=templates/pip.j2 dest=/root/.pip/pip.conf owner=root
      tags: configuration

    - name: install insecure ssh config for root
      template: src=files/insecure_config_proxy dest=~/.ssh/config mode=0600

- include: site-base.yml
