# order matters!
---
- hosts: all
  user: root

  roles:
    - proxy

  tasks:
    - name: install insecure ssh config for root
      template: src=files/insecure_config_proxy dest=~/.ssh/config mode=0600

- include: site-base.yml proxy_is_set=True
# deploy your rails app here (you should deploy it on the machines where you deployed passenger)
#- include: site-daily.yml
- include: playbooks/setup-dri_app.yml proxy_is_set=True
