---
- name: check for percona tools install
  command: dpkg -l | grep percona-toolkit | grep {{ percona_toolkit_version }}
  register: result
  ignore_errors: True
  when: active_master is defined

- name: Deliver percona-tools deb
  command: >
	chdir=/tmp
	creates=/tmp/percona-toolkit_{{ percona_toolkit_version }}_all.deb
	wget http://www.percona.com/redir/downloads/percona-toolkit/{{ percona_toolkit_version }}/deb/percona-toolkit_{{ percona_toolkit_version }}_all.deb
  when: active_master is defined and result.rc=1

- name: Install percona-tools
  command: dpkg -i /tmp/percona-toolkit_{{ percona_toolkit_version }}_all.deb
  when: active_master is defined and result.rc=1

- name: create active master percona sql user
  mysql_user: name=percona_user password={{ percona_user_pass }} host=localhost priv=*.*:ALL state=present
  when: active_master is defined

- name: create passive master percona sql user
  mysql_user: name=percona_user password={{ percona_user_pass }} host={{ groups.mysql_replicated[0] }}  priv=*.*:ALL state=present
  when: active_master is not defined




