---
- name: check for percona tools install
  shell: dpkg -l | grep percona-toolkit | grep {{ percona_toolkit_version }}
  register: result
  ignore_errors: True
  when: active_master is defined

- name: Deliver percona-tools deb
  command: wget http://www.percona.com/redir/downloads/percona-toolkit/{{ percona_toolkit_version }}/deb/percona-toolkit_{{ percona_toolkit_version }}_all.deb chdir=/tmp creates=/tmp/percona-toolkit_{{ percona_toolkit_version }}_all.deb
  when: result.rc != 0 and active_master is defined

- name: Install percona-tools
  command: dpkg -i /tmp/percona-toolkit_{{ percona_toolkit_version }}_all.deb
  when: active_master is defined and result.rc != 0

- name: create active master percona sql user
  mysql_user: name=percona_user password={{ percona_user_pass }} host=localhost priv=*.*:ALL state=present
  when: active_master is defined

- name: create passive master percona sql user
  mysql_user: name=percona_user password={{ percona_user_pass }} host={{ groups.mysql_replicated[1] }}  priv=*.*:ALL state=present
  when: active_master is not defined

- name: deliver percona check script
  template: src=percona-check.sh.yml dest=/usr/sbin/percona-check.sh mode=0754
  when: active_master is defined

- name: create sql check cronjob
  cron: name="check sql replication consistency" hour="4,16" weekday="1-5" job="/usr/sbin/percona-check.sh {{ admin_email }}"
  when: active_master is defined
