---
- copy: src=precise/requirements.txt dest=/home/{{rvm_user}}/requirements.txt owner={{rvm_user}} group={{rvm_user}}
#  notify: restart buildmaster

- apt: name={{ item }} state=present
  with_items:
    - python-virtualenv
    - python-dev
    - python-pip
    - python-jinja2
    - python-migrate
    - python-twisted

- copy: src=pip-1.5.2.tar.gz dest=/tmp/pip-1.5.2.tar.gz
- command: pip install /tmp/pip-1.5.2.tar.gz creates=/usr/local/bin/pip

- pip: executable="tsocks pip" name=sqlalchemy version=0.7.10 state=present
- pip: executable="tsocks pip" name=buildbot state=present
- pip: executable="tsocks pip" name=buildbot-slave state=present

# or do this
#- command: chdir=/home/{{rvm_user}} pip install  -i http://c.pypi.python.org/simple -r requirements.txt

- command: creates=/home/{{rvm_user}}/masters/master.cfg chdir=/home/{{rvm_user}} buildbot create-master masters
#  notify: restart buildmaster

- copy: src=precise/master.cfg dest=/home/{{rvm_user}}/masters/master.cfg owner={{rvm_user}} group={{rvm_user}}
#  notify: restart buildmaster

- copy: src=precise/master.json dest=/home/{{rvm_user}}/masters/master.json owner={{rvm_user}} group={{rvm_user}}
#  notify: restart buildmaster

- copy: src=precise/SimpleConfig.py dest=/home/{{rvm_user}}/masters/SimpleConfig.py owner={{rvm_user}} group={{rvm_user}}
#  notify: restart buildmaster

- template: src=myconfig.json dest=/home/{{rvm_user}}/myconfig.json

- file: path=/home/{{rvm_user}} owner={{rvm_user}} group={{rvm_user}} recurse=yes

- apt: name=supervisor state=present
- template: src=buildbot.conf dest=/etc/supervisor/conf.d/buildbot.conf
- service: name=supervisor enabled=yes
