# See also http://mvnrepository.com/artifact/org.fcrepo/fcrepo-webapp-fedora/${fedora_version}
---
- name: Check variable fedora_version is set
  fail: msg="Please set 'fedora_version' variable in the playbook"
  when: fedora_version is not defined

# setup db in top level site.yml
#- include: mysql.yml

- name: Download Fedora Commons
  #action: get_url url=http://ftp.heanet.ie/mirrors/www.apache.org/dist/lucene/solr/4.1.0/solr-4.1.0.tgz dest=/tmp/solr-4.1.0.tgz
  shell: curl http://repo1.maven.org/maven2/org/fcrepo/fcrepo-installer/${fedora_version}/fcrepo-installer-${fedora_version}.jar > /tmp/fcrepo-installer-${fedora_version}.jar creates=/tmp/fcrepo-installer-${fedora_version}.jar

- name: Upload install.properties file for automated install
  template: src=fedora-install-properties-mysql.j2 dest=/tmp/fedora-install.properties owner=tomcat group=tomcat

- name: Setup directory
  file: path=/opt/fedora state=directory owner=tomcat group=tomcat

- name: Run automated install of fedora-commons
  command: java -jar /tmp/fcrepo-installer-${fedora_version}.jar /tmp/fedora-install.properties creates=/opt/fedora/server/config/fedora.fcfg
  sudo: True
  sudo_user: tomcat

## could be smarter below here as a loop can be written
- name: Install tomcat context for fop
  template: src=fop-xml.j2 dest=/etc/tomcat6/Catalina/localhost/fop.xml owner=tomcat group=tomcat

- name: Install tomcat context for imagemanip
  template: src=imagemanip-xml.j2 dest=/etc/tomcat6/Catalina/localhost/imagemanip.xml owner=tomcat group=tomcat

- name: Install tomcat context for saxon
  template: src=saxon-xml.j2 dest=/etc/tomcat6/Catalina/localhost/saxon.xml owner=tomcat group=tomcat

## deploy the fedora context last
- name: Install tomcat context for fedora
  template: src=fedora-xml.j2 dest=/etc/tomcat6/Catalina/localhost/fedora.xml owner=tomcat group=tomcat
