---
  #
  # mod_passenger
  #
  - name: install mod_passenger dependencies
    action: yum pkg=$item state=present
    with_items:
      - httpd
      - httpd-devel
      - apr-devel
      - apr-util-devel

  - name: start and enable httpd
    action: service name=httpd state=started enabled=yes

#
# ruby 1.8.7 
#
#  - name: download passenger release file
#    command: curl -O http://passenger.stealthymonkeys.com/rhel/6/passenger-release.noarch.rpm chdir=/tmp creates=/tmp/passenger-release.noarch.rpm

#  - name: install passenger release file
#    command: rpm -ivH /tmp/passenger-release.noarch.rpm creates=/etc/yum.repos.d/passenger.repo

#  - name: install mod passenger
#    yum: name=mod_passenger state=present
#    notify:
#      - restart httpd

#
# passenger from rvm/ruby much more flexible and reliable
#

  # 3.0.19 was the last known good version, now at 4.0.2
  - name: install mod_passenger
    action: shell ${rvm_bindir}/gem install passenger creates=${gemdir.stdout}/bin/passenger-install-apache2-module
    sudo: False

  - name: register passenger version variable
    action: shell source ${home_directory}/.rvm/environments/default && ${gemdir.stdout}/bin/passenger-config --version
    register: passenger_version
    sudo: False

  - name: pre-configure mod_passenger
    action: shell source ${home_directory}/.rvm/environments/default && ${gemdir.stdout}/bin/passenger-install-apache2-module -a creates=${gemdir.stdout}/gems/passenger-${passenger_version.stdout}/libout/apache2/mod_passenger.so
    sudo: False

  - name: configure apache for mod_passenger
    action: template src=../templates/passenger.j2 dest=/etc/httpd/conf.d/passenger.conf
    notify:
      - restart httpd

  - name: configure rails app
    action: template src=$item dest=/etc/httpd/conf.d/rails-app.conf
    first_available_file:
      - ../templates/rails-app-${host_group}.j2
      - ../templates/rails-app.j2
    notify:
      - restart httpd
