---
- file: path=/var/lib/rrdcached/journal/ state=directory

- apt: name={{item}} state=present
  with_items:
    - collectd
    - rrdcached
    - apache2
    - libconfig-general-perl
    - librrds-perl
    - libregexp-common-perl
    - libhtml-parser-perl

- template: src=precise/collectd-server.conf dest=/etc/collectd/collectd.conf owner=root group=root
  notify: restart collectd

- copy: src=precise/collectd-apache.conf dest=/etc/apache2/sites-enabled/collectd owner=root group=root
  notify: restart apache2

