---
- name: Install dependancies
  apt: name={{item}} state=present
  with_items:
    - imagemagick
    - libgraphicsmagick1-dev
    - npm
    - clamav
    - libclamav-dev
    - ffmpeg
    - libavcodec-extra-53
    - libmysqlclient-dev
    - mysql-client
    - ghostscript
