---
- apt: name={{ item }} state=present
  with_items:
    - python-virtualenv
    - python-pip

- file: path=/opt/src state=directory
- copy: src=pip-1.5.2.tar.gz dest=/opt/src/pip-1.5.2.tar.gz
- command: pip install /opt/src/pip-1.5.2.tar.gz creates=/usr/local/bin/pip
