---
  - name: Set up ruby and rails dependancies
    apt: pkg=$item state=present
    with_items:
      - build-essential
      - openssl
      - libreadline6
      - libreadline6-dev
      - curl
      - git-core
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libyaml-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev
      - libxslt1-dev
      - autoconf
      - libc6-dev
      - libncurses5-dev
      - automake
      - libtool
      - bison
      - subversion
      - gawk
      - libgdbm-dev
      - pkg-config
      - libffi-dev

  - name: install rvm
    sudo: True
    sudo_user: $rvm_user
    command: bash -lc 'curl -4 -L https://get.rvm.io | bash -s 1.23.7' creates=${rvm_bindir}/rvm

  - name: install ruby ${ruby_version}
    sudo: True
    sudo_user: $rvm_user
    command: bash -lc 'rvm install ${ruby_version}'

  - name: use ruby ${ruby_version} by default
    sudo: True
    sudo_user: $rvm_user
    command: bash -lc 'rvm alias create default ${ruby_version}'

  # register variables for later use
  - name: register gem dir variable
    sudo: True
    sudo_user: $rvm_user
    command: bash -lc 'rvm gemdir'
    register: gemdir

  - name: register ruby version variable
    sudo: True
    sudo_user: $rvm_user
    command: bash -lc 'rvm current'
    register: ruby_version
