---
- name: Install mysql client and server
  apt: pkg={{item}} state=present
  with_items:
    - mysql-client
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb
  notify:
    - restart mysql

- name: enable mysqld service
  action: service name=mysql state=started enabled=yes

- name: create my.cnf file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf backup=yes
  notify:
    - restart mysql

- include: secure.yml
