---
- apt_repository: repo="ppa:thwint/tom" state=present

- apt: name={{item}} state=present
  with_items:
    - apache2
    - xymon
    - xymon-plugins

- command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify:
    - restart apache2

- service: name=apache2 state=started

- file: path=/etc/xymon/hosts.d state=directory owner=root group=root

- copy: src=precise/dnsreg.cfg dest=/etc/xymon/tasks.d/dnsreg.cfg owner=root group=root mode=0644
- copy: src=precise/dnsreg.sh dest=/usr/lib/xymon/client/ext/dnsreg.sh owner=root group=root mode=0755

- copy: src=precise/tasks.cfg dest=/etc/xymon/tasks.cfg owner=root group=root mode=0644
  notify:
    - restart xymon

- template: src=precise/{{item}} dest=/etc/xymon/{{item}} mode=0644
  with_items:
    - hosts.cfg
  notify:
    - restart xymon

- copy: src=precise/{{item}} dest=/etc/xymon/{{item}} mode=0644
  with_items:
    - alerts.cfg
  notify:
    - restart xymon

- template: src=precise/{{item}} dest=/etc/xymon/hosts.d/{{item}} mode=0644
  with_items:
    - 000-general.cfg
    - 100-dri.cfg
  notify:
    - restart xymon
