---
- apt_repository: repo="ppa:thwint/tom" state=present

- apt: name={{item}} state=present
  with_items:
    - apache2
    - xymon
    - xymon-plugins

- command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify:
    - restart apache2

- service: name=apache2 state=started

- file: path=/etc/xymon/hosts.d state=directory owner=root group=root

- template: src=precise/{{item}} dest=/etc/xymon/{{item}} mode=0644
  with_items:
    - hosts.cfg
  notify:
    - restart xymon

- template: src=precise/{{item}} dest=/etc/xymon/hosts.d/{{item}} mode=0644
  with_items:
    - 000-general.cfg
    - 100-dri.cfg
  notify:
    - restart xymon
