---
- name: save state with etckeeper
  command: etckeeper commit "Commit by ansible, saving state."
  ignore_errors: True
  tags:
    - etckeeper
    - etckeeper-commit

- name: repack git directory
  command: git gc chdir=/etc
  ignore_errors: True
  tags:
    - etckeeper
    - etckeeper-gc

- name: initialise etckeeper
  command: etckeeper init creates=/etc/.git/config
  tags: etckeeper
