---
- copy: src=precise/requirements.txt dest=/home/{{rvm_user}}/requirements.txt owner={{rvm_user}} group={{rvm_user}}
#  notify: restart buildmaster

- apt: name={{ item }} state=present
  with_items:
    - python-virtualenv
    - python-dev
    - python-pip
    - python-jinja2
    - python-migrate
    - python-twisted
- pip: name=sqlalchemy version=0.7.10 state=present
  ignore_errors: true
- pip: name=buildbot state=present
  ignore_errors: true
- pip: name=buildbot-slave state=present
  ignore_errors: true
# or do this
#- command: chdir=/home/{{rvm_user}} pip install  -i http://c.pypi.python.org/simple -r requirements.txt

- apt: name=supervisor state=present
- template: src=buildbot-slave.conf dest=/etc/supervisor/conf.d/buildbot-slave.conf
- service: name=supervisor state=restarted enabled=yes
