---
- include: repos.yml

- name: Enable EPEL
  action: yum pkg=$item state=present
  with_items:
    - epel-release
    - yum-plugin-fastestmirror

- name: Clear out cache
  command: yum -y clean all

- name: Common packages
  action: yum pkg=$item state=latest
  with_items:
    - tsocks
    - ansible
    - git
    - etckeeper
    - python-pip
    - python-virtualenv
    - python-setuptools
    - MySQL-python
    - python-psycopg2
    - avahi
    - avahi-dnsconfd
    - nc
    - libselinux-python
    - dstat
  notify:
    - startup avahi-daemon and avahi-dnsconfd

- name: Stop and disable iptables
  action: service name=$item state=stopped enabled=no
  with_items:
    - iptables
