---
- apt: name={{item}} state=present
  with_items:
    - apache2
    - nagios3
    - nagios-plugins

- template: src=precise/passwd dest=/etc/nagios3/htpasswd.users owner=root group=www-data mode=0640
  notify: restart apache2

- template: src=precise/cgi.cfg dest=/etc/nagios3/cgi.cfg owner=root group=root mode=0644
  notify: restart nagios

- template: src=precise/apache2.conf dest=/etc/nagios3/apache2.conf owner=root group=root mode=0644
  notify: restart apache2

- template: src=precise/config.inc.php dest=/usr/share/nagios3/htdocs/config.inc.php owner=root group=root mode=0644
  notify: restart nagios

- template: src=precise/commands.cfg dest=/etc/nagios3/commands.cfg owner=root group=root mode=0644
  notify: restart nagios

- file: path=/etc/nagios3/conf.d/{{item}} state=absent
  with_items:
    - extinfo_nagios2.cfg
    - hostgroups_nagios2.cfg
    - localhost_nagios2.cfg
    - services_nagios2.cfg
 
- template: src=precise/{{ item  }} dest=/etc/nagios3/conf.d/{{ item }} owner=root group=root mode=0644
  with_items:
     - all.cfg
     - servers.cfg
     - monitoring.cfg
     - haproxy.cfg
     - webservers.cfg
     - resque_workers.cfg
     - fedora.cfg
     - solr.cfg
     - shibboleth.cfg
     - mysql_replicated.cfg
     - ldap_replicated.cfg
     - radosgw.cfg
     - buildbot.cfg
     - redis.cfg
     - sites.cfg
  notify:
    - restart nagios
    - restart apache2

- service: name=nagios3 state=started enabled=yes
- service: name=apache2 state=started enabled=yes
