---
- apt_key: url=https://get.docker.io/gpg state=present
- apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
- apt: pkg=lxc-docker state=latest update_cache=yes cache_valid_time=3600
