---
## boiler plate
- name: Install dependancies
  apt: name=$item state=present update-cache=yes
  with_items:
    - git
    - bzr
    - etckeeper
    - curl
    - avahi-daemon
    - avahi-utils
    - avahi-discover
    - avahi-dnsconfd
    - ruby-json
    - facter

# enable sendmail
- apt: name=sendmail state=present
- template: src=sendmail.mc dest=/etc/mail/sendmail.mc
- service: name=sendmail state=restarted enabled=yes

# enable ntp
- apt: name=ntp state=present
- template: src=ntp.conf dest=/etc/ntp.conf
- service: name=ntp state=restarted enabled=yes
