---
- apt_repository: repo="ppa:webupd8team/java" state=present
- shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
- apt: name={{item}} state=present
  with_items:
    - oracle-java7-set-default
    - oracle-java7-installer
- command: update-java-alternatives -s java-7-oracle

- apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
- apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.3/debian stable main" state=present
- apt: name=logstash state=present

- copy: src=rsyslog.conf dest=/etc/logstash/conf.d/rsyslog.conf owner=root group=root
  notify:
    - restart logstash

- copy: src=logstash dest=/etc/default/logstash owner=root group=root
  notify:
    - restart logstash

#- apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main" state=present
#- apt: name=elasticsearch state=present
