# order matters!
---
- hosts: kraken-sl
  user: vagrant
  sudo: True

  vars_files:
    - ../vars/global.yml
    - ../vars/${ansible_distribution}.yml

  vars:
    host_group: nuig-rnag

  roles:
    - role: proxy
      proxy_server: proxy.tchpc.tcd.ie
      proxy_port: 8080
      socks_server: 134.226.112.43
      socks_port: 1080
    - etckeeper
    - common
    - role: ceph-base
      mon_port: 6789                                                              
      mon_ip_a: ${ansible_default_ipv4.address}                                   
      mon_fqdn_a: ${ansible_default_ipv4.address}                                 
      mds_fqdn_a: ${ansible_default_ipv4.address}                                 
      osd_fqdn_0: ${ansible_default_ipv4.address}                                 
      osd_fqdn_1: ${ansible_default_ipv4.address}
      radosgw_hostname: ${ansible_hostname}

  tasks:

  handlers:
