# order matters!
---
- hosts: hydra
  user: vagrant
  sudo: True

  vars_files:
    - ../vars/global.yml
    - ../vars/${ansible_distribution}.yml

  vars:
    host_group: nuig-rnag
    solr_version: 4.0.0
    fedora_version: 3.6.2

  roles:
    - etckeeper
    - common
    - role: rvm-common
      rvm_user: vagrant
      ruby_version: 2.0.0-p195
      rvm_home: /home/${rvm_user}/.rvm
      rvm_bindir: ${rvm_home}/bin
    - role: rvm-passenger
      rvm_user: vagrant
      ruby_version: 2.0.0-p195
      rvm_home: /home/${rvm_user}/.rvm
      rvm_bindir: ${rvm_home}/bin
    - tomcat
    - redis
    - role: mysql
      mysql_root_password: CHANGEME

  tasks:
    - name: /root/.pip
      file: path=/root/.pip/ owner=root  mode=0755 state=directory

    - name: write /root/.pip/pip.conf
      action: template src=../templates/pip.j2 dest=/root/.pip/pip.conf owner=root
      tags: configuration

    - name: install insecure ssh config for root
      template: src=../files/insecure_config_proxy dest=~/.ssh/config mode=0600
      sudo: False

    ## install phantomjs for testing
    - include: ../tasks/phantomjs.yml

    ## must configure vhosts to look for a rails app deployment to serve out
 #  - name: configure rails app
 #    action: template src=$item dest=/etc/httpd/conf.d/rails-app.conf
 #    first_available_file:
 #      - ../templates/rails-app-${host_group}.j2
 #      - ../templates/rails-app.j2
 #    notify:
 #      - restart httpd 

    ## additional dependancies needed for hydra-head
    - name: create db 'dridb'
      action: mysql_db db=dridb state=present

    # usernames and passwords should be included from a file outside of this git-repo, for now this is developmental.
    - name: create user 'driuser' with password 'dripass' for 'dridb' and grant all priveleges
      action: mysql_user state=present name=driuser password=dripass priv=dridb.*:ALL

    #- include: ../tasks/postgresql-sl.yml
    - include: ../tasks/solr-sl.yml
    - include: ../tasks/fedora-sl.yml

    # optional can be commented out, ruby versions are taken from a previous task
#    - name: Run bundle
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && bundle chdir=/vagrant/nuig-rnag
#
#    - name: generate assets
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production assets:precompile chdir=/vagrant/nuig-rnag
#
#    - name: load schema
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production db:schema:load chdir=/vagrant/nuig-rnag
#
#    - name: db migrate
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production db:migrat chdir=/vagrant/nuig-rnag

  handlers:
    - include: ../handlers/main.yml
