# order matters!
---
- hosts: kraken-sl
  user: vagrant
  sudo: True

  vars_files:
    - ../vars/global.yml
    - ../vars/${ansible_distribution}.yml

  vars:
    host_group: nuig-rnag
    solr_version: 4.0.0
    fedora_version: 3.6.2

    # buildbot
    venv_user: vagrant

    # user that will have rvm and ruby etc...
    rvm_user: vagrant

    # RVM/RoR related
    home_directory: /home/${rvm_user}
    rvm_home: ${home_directory}/.rvm
    rvm_bindir: ${rvm_home}/bin

    # Ceph
    mon_port: 6789                                                              
    mon_ip_a: ${ansible_default_ipv4.address}                                   
    mon_fqdn_a: ${ansible_default_ipv4.address}                                 
    mds_fqdn_a: ${ansible_default_ipv4.address}                                 
    osd_fqdn_0: ${ansible_default_ipv4.address}                                 
    osd_fqdn_1: ${ansible_default_ipv4.address}

  roles:
    - etckeeper
    - common
    - tomcat
    - redis

  tasks:
    ## install rvm and basic ruby install
    - include: ../tasks/rvm-setup-sl.yml
    - include: ../tasks/rvm-setup-common.yml

    ## install rails and mod passenger
    - include: ../tasks/rails-sl.yml

    ## install phantomjs for testing
    ## must configure vhosts to look for a rails app deployment to serve out
    - include: ../tasks/phantomjs.yml

    ## additional dependancies needed for hydra-head
    - include: ../tasks/mysql-sl.yml
    #- include: ../tasks/postgresql-sl.yml
    - include: ../tasks/solr-sl.yml
    - include: ../tasks/fedora-sl.yml

    ## storage component
    #- include: ../tasks/ceph-sl.yml

    ## continuous builder/tester
    #- include: ../tasks/buildbot.yml

    # optional can be commented out, ruby versions are taken from a previous task
#    - name: Run bundle
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && bundle chdir=/vagrant/nuig-rnag
#
#    - name: generate assets
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production assets:precompile chdir=/vagrant/nuig-rnag
#
#    - name: load schema
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production db:schema:load chdir=/vagrant/nuig-rnag
#
#    - name: db migrate
#      shell: source ${home_directory}/.rvm/environments/${ruby_version.stdout}@global && rake RAILS_ENV=production db:migrat chdir=/vagrant/nuig-rnag

  handlers:
    - include: ../handlers/ceph-sl.yml
