# order matters!
---
- hosts: all
  user: vagrant
  sudo: True

  tasks:
    - name: remove proxy.sh from system
      file: path=/etc/profile.d/proxy.sh state=absent

    - name: remove proxy configuration from /etc/yum.conf
      lineinfile: dest=/etc/yum.conf regexp="^proxy=" state=absent

    - name: remove proxy configuration from /etc/apt/apt.conf
      lineinfile: dest=/etc/apt/apt.conf regexp="^Acquire::http::Proxy" state=absent

    - lineinfile: dest=/etc/wgetrc regexp="^http_proxy" state=absent
    - lineinfile: dest=/etc/wgetrc regexp="^https_proxy" state=absent
    - lineinfile: dest=/etc/wgetrc regexp="^ftp_proxy" state=absent

    - lineinfile: dest=/root/.curlrc regexp="^proxy = " state=absent
    - lineinfile: dest=/home/{{rvm_user}}/.curlrc regexp="^proxy = " state=absent

    - lineinfile: dest=/root/.gemrc regexp="^gem.*--http-proxy" state=absent
    - lineinfile: dest=/home/{{rvm_user}}/.gemrc regexp="^gem.*--http-proxy" state=absent

    - lineinfile: dest=/root/.pip/pip.conf regexp="^proxy =" state=absent
    - lineinfile: dest=/home/{{rvm_user}}/.pip/pip.conf regexp="^proxy =" state=absent

    - lineinfile: dest=/root/.ssh/config regexp="ProxyCommand nc -x" state=absent
    - lineinfile: dest=/home/{{rvm_user}}/.ssh/config regexp="ProxyCommand nc -x" state=absent
