# order matters!
---
- hosts: all
  user: vagrant
  sudo: True

  tasks:
    - name: remove proxy.sh from system
      file: path=/etc/profile.d/proxy.sh state=absent

    - name: remove proxy configuration from /etc/yum.conf
      lineinfile: dest=/etc/yum.conf regexp="^proxy=" state=absent

    - name: remove proxy configuration from /root/.curlrc
      lineinfile: dest=/root/.curlrc regexp="^proxy = " state=absent

    - name: remove proxy configuration from /root/.gemrc
      lineinfile: dest=/root/.gemrc regexp="^gem.*--http-proxy" state=absent

    - name: remove proxy configuration from /root/.pip/pip.conf
      lineinfile: dest=/root/.pip/pip.conf regexp="^proxy =" state=absent

    - name: remove ssh configuration from /root/.ssh/config
      lineinfile: dest=/root/.ssh/config regexp="ProxyCommand nc -x" state=absent
