---
- hosts: mysql_replicated
  user: root

  tasks:

  - name: Run percona and email problem records to admin email
    shell: pt-table-sync --print --user=percona_user --password={{ percona_user_pass }} --sync-to-master {{ groups.mysql_replication[0] }}
    when: active_master is defined
