# order matters!
---
- hosts: passenger;fedora;solr
  user: root
  ## dummy group just to pull in needed information for selfcontained runs

- hosts: mysql
  user: root

  roles:
    - { role: ../../roles/mysql }

  tasks:
    ## Create databases needed for public and private head
    - name: create db '{{ db_name }}'
      mysql_db: db={{ db_name }} state=present

    - name: create user '{{ db_user }}' with password '{{ db_pass }}' for '{{ db_name }}' and grant all priveleges
      mysql_user: state=present name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL host={{ groups['passenger'][0] }}

- hosts: dri_app
  user: root

  tasks:
    - name: Enable RPM Fusion
      yum: name=yum-conf-rpmfusion state=present

    - name: Install dependancies
      yum: name=$item state=present
      with_items:
        - ImageMagick
        - ImageMagick-devel
        - npm
        - clamav
        - clamav-devel
        - ffmpeg
        - ffmpeg-devel
        - mysql-devel

    ## must configure vhosts to look for a rails app deployment to serve out
    - name: configure rails app - private and public head config
      action: template src=$item dest=/etc/httpd/conf.d/rails-app-{{ host_group }}.conf
      first_available_file:
        - ../templates/rails-app-${host_group}.j2
        - ../templates/rails-app.j2
      notify:
        - restart httpd

    - name: Drop in auth-key so keyforwarding can work
      authorized_key: user={{rvm_user}} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: Drop in private ssh key from jenkins account
      copy: src=~/.ssh/id_rsa dest=~{{ rvm_user }}/.ssh/id_rsa owner={{rvm_user}} group={{rvm_user}} mode=0700

    - name: Make home directory accessible by apache and friends
      file: path=/home/{{ rvm_user }} mode=0755 state=directory

  handlers:
    - include: ../handlers/main.yml

- include: setup-dri_app-nuig-rnag.yml
- include: setup-dri_app-nuig-rnag-public.yml

- hosts: dri_app
  user: root

  tasks:
    - name: Install redis-server
      yum: name=redis state=present

    - name: Start and enable redis
      service: name=redis enabled=yes state=started

    - template: src=../templates/resque.init dest=/etc/init.d/{{ host_group }} mode=0755
    - command: chkconfig --add {{ host_group }}
    - service: name={{ host_group }} enabled=yes state=started

    - name: Symlink public head
      file: src=/home/{{rvm_user}}/{{ host_group }}-public/public dest=/var/www/html/repository state=link

    - name: Symlink admin head
      file: src=/home/{{rvm_user}}/{{ host_group }}/public dest=/var/www/html/admin state=link

    - name: Restart Apache
      service: name=httpd state=restarted

    - name: Drop in a stub page to link to the two rails apps
      template: src=../templates/index-{{ host_group }}.html dest=/var/www/html/index.html mode=0644
