# order matters!
---
- hosts: passenger;fedora;solr,mysql
  user: root
  ## dummy group just to pull in needed information for selfcontained runs

## deploy the rails applications - private head
- hosts: dri_app
  user: $rvm_user

  tasks:
    - command: git config --global core.compression -1

    # Clone the repositories
    - name: clone {{ host_group }} code - private head
      git: repo=ssh://git@lonsdale.tchpc.tcd.ie/navr/{{ host_group }} dest=/home/{{rvm_user}}/{{ host_group }} version=develop update=yes

    # configure up app 1
    # optional can be commented out, ruby versions are taken from a previous task
    - name: Configure database
      template: src=../templates/nuig-rnag/$item dest=/home/{{rvm_user}}/{{ host_group }}/config/$item
      with_items:
        - database.yml
        - fedora.yml
        - solr.yml

    - name: Run bundle for {{ host_group }}
      command: bash -lc 'bundle install' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: generate assets
      command: bash -lc 'rake RAILS_ENV=production assets:precompile RAILS_RELATIVE_URL_ROOT="/admin"' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: load schema
      command: bash -lc 'rake RAILS_ENV=production db:schema:load' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: db migrate
      command: bash -lc 'rake RAILS_ENV=production db:migrate' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: db seed
      command: bash -lc 'rake RAILS_ENV=production db:migrate' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: Install redis-server
      yum: name=redis state=present

    - name: Start and enable redis
      service: name=redis enabled=yes state=started

    - template: src=../templates/resque.init dest=/etc/init.d/{{ host_group }} mode=0755
    - command: chkconfig --add {{ host_group }}
    - service: name={{ host_group }} enabled=yes state=started

    - name: Symlink admin head
      file: src=/home/{{rvm_user}}/{{ host_group }}/public dest=/var/www/html/admin state=link

    - name: Restart Apache
      service: name=httpd state=restarted
