# order matters!
---
- hosts: passenger;fedora;solr
  user: root
  ## dummy group just to pull in needed information for selfcontained runs

- hosts: mysql
  user: root

  roles:
    - { role: ../../roles/mysql }

  tasks:
    ## Create databases needed for public and private head
    - name: create db '{{ db_name }}'
      mysql_db: db={{ db_name }} state=present

    - name: create user '{{ db_user }}' with password '{{ db_pass }}' for '{{ db_name }}' and grant all priveleges
      mysql_user: state=present name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL host={{ groups['passenger'][0] }}

- hosts: dri_app
  user: root

  tasks:
    - name: Enable RPM Fusion
      yum: name=yum-conf-rpmfusion state=present

    - name: Install dependancies
      yum: name=$item state=present
      with_items:
        - ImageMagick
        - ImageMagick-devel
        - npm
        - clamav
        - clamav-devel
        - ffmpeg
        - ffmpeg-devel
        - mysql-devel

    ## must configure vhosts to look for a rails app deployment to serve out
    - name: configure rails app - private and public head config
      action: template src=$item dest=/etc/httpd/conf.d/rails-app-{{ host_group }}.conf
      first_available_file:
        - ../templates/rails-app-${host_group}.j2
        - ../templates/rails-app.j2
      notify:
        - restart httpd

    - name: Drop in auth-key so keyforwarding can work
      authorized_key: user={{rvm_user}} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: Make home directory accessible by apache and friends
      file: path=/home/{{ rvm_user }} mode=0755 state=directory

  handlers:
    - include: ../handlers/main.yml

## deploy the rails applications - public head
- hosts: dri_app
  user: $rvm_user

  tasks:
    - command: git config --global core.compression -1

    - name: clone {{ host_group }}-public code - public head
      git: repo=git@dev.forasfeasa.ie:{{ host_group }}-public dest=/home/{{rvm_user}}/{{ host_group }}-public version=develop update=yes

    # optional can be commented out, ruby versions are taken from a previous task
    - name: Configure database
      template: src=../templates/nuig-rnag-public/$item dest=/home/{{rvm_user}}/{{ host_group }}-public/config/$item
      with_items:
        - database.yml
        - fedora.yml
        - solr.yml

    - name: Run bundle for {{ host_group }}-public
      command: bash -lc 'bundle install' chdir=/home/{{rvm_user}}/{{ host_group }}-public
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: generate assets
      command: bash -lc 'rake RAILS_ENV=production assets:precompile RAILS_RELATIVE_URL_ROOT="/repository"' chdir=/home/{{rvm_user}}/{{ host_group }}-public
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: load schema
      command: bash -lc 'rake RAILS_ENV=production db:schema:load' chdir=/home/{{rvm_user}}/{{ host_group }}-public
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: db migrate
      command: bash -lc 'rake RAILS_ENV=production db:migrate' chdir=/home/{{rvm_user}}/{{ host_group }}-public
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: db seed
      command: bash -lc 'rake RAILS_ENV=production db:seed' chdir=/home/{{rvm_user}}/{{ host_group }}-public
      environment:
        DRI_BUNDLE_ENV: tchpc

## deploy the rails applications - private head
- hosts: dri_app
  user: $rvm_user

  tasks:
    - command: git config --global core.compression -1

    # Clone the repositories
    - name: clone {{ host_group }} code - private head
      git: repo=ssh://git@lonsdale.tchpc.tcd.ie/navr/{{ host_group }} dest=/home/{{rvm_user}}/{{ host_group }} version=develop update=yes

    # configure up app 1
    # optional can be commented out, ruby versions are taken from a previous task
    - name: Configure database
      template: src=../templates/nuig-rnag/$item dest=/home/{{rvm_user}}/{{ host_group }}/config/$item
      with_items:
        - database.yml
        - fedora.yml
        - solr.yml

    - name: Run bundle for {{ host_group }}
      command: bash -lc 'bundle install' chdir=/home/{{rvm_user}}/{{ host_group }}
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: generate assets
      command: bash -lc 'rake RAILS_ENV=production assets:precompile RAILS_RELATIVE_URL_ROOT="/admin"' chdir=/home/{{rvm_user}}/{{ host_group }}
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: load schema
      command: bash -lc 'rake RAILS_ENV=production db:schema:load' chdir=/home/{{rvm_user}}/{{ host_group }}
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: db migrate
      command: bash -lc 'rake RAILS_ENV=production db:migrate' chdir=/home/{{rvm_user}}/{{ host_group }}
      environment:
        DRI_BUNDLE_ENV: tchpc

    - name: db seed
      command: bash -lc 'rake RAILS_ENV=production db:migrate' chdir=/home/{{rvm_user}}/{{ host_group }}
      environment:
        DRI_BUNDLE_ENV: tchpc

- hosts: dri_app
  user: root

  tasks:
    - name: Install redis-server
      yum: name=redis state=present

    - name: Start and enable redis
      service: name=redis enabled=yes state=started

    - template: src=../templates/resque.init dest=/etc/init.d/{{ host_group }} mode=0755
    - command: chkconfig --add {{ host_group }}
    - service: name={{ host_group }} enabled=yes state=started

    - name: Symlink public head
      file: src=/home/{{rvm_user}}/{{ host_group }}-public/public dest=/var/www/html/repository state=link

    - name: Symlink admin head
      file: src=/home/{{rvm_user}}/{{ host_group }}/public dest=/var/www/html/admin state=link

    - name: Restart Apache
      service: name=httpd state=restarted

    - name: Drop in a stub page to link to the two rails apps
      template: src=../templates/index-{{ host_group }}.html dest=/var/www/html/index.html mode=0644
