---
- hosts: all
  user: root

  tasks:
    - yum: name=epel-release state=present
    - yum: name=libselinux-python state=present

    - name: Upload public ssh key
      authorized_key: user=root key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

    - name: Restorecon of system
      command: restorecon -r /root
