# order matters!
---
- hosts: passenger;fedora;solr;mysql;mysql_replicated
  user: root
  ## dummy group just to pull in needed information for selfcontained runs

## deploy the rails applications - private head
- hosts: dri_app
  user: $rvm_user

  tasks:
    - command: git config --global core.compression -1

    - command: git config --global http.proxy http://{{proxy_server}}:{{proxy_port}}
      when: proxy_is_set is defined

    - command: git config --global https.proxy http://{{proxy_server}}:{{proxy_port}}
      when: proxy_is_set is defined

    # Clone the repositories
    - name: clone {{ host_group }} code - private head
      git: repo=ssh://git@tracker.dri.ie/navr/{{ host_group }} dest=/home/{{rvm_user}}/{{ host_group }} version={{deploy_branch}} update=yes
      ignore_errors: True

    # configure up app 1
    # optional can be commented out, ruby versions are taken from a previous task
    - name: Configure database
      template: src=../templates/nuig-rnag/$item dest=/home/{{rvm_user}}/{{ host_group }}/config/$item
      with_items:
        - database.yml
        - fedora.yml
        - solr.yml
        - redis.yml

    - template: src=../templates/nuig-rnag/settings.yml dest=/home/{{rvm_user}}/{{ host_group }}/config/settings.local.yml

    - name: Run bundle for {{ host_group }}
      command: bash -lc 'bundle install' chdir=/home/{{rvm_user}}/{{ host_group }}
      when: proxy_is_set is defined
      environment:
        http_proxy: http://{{proxy_server}}:{{proxy_port}}
        https_proxy: http://{{proxy_server}}:{{proxy_port}}

    - name: Run bundle for {{ host_group }}
      command: bash -lc 'bundle install' chdir=/home/{{rvm_user}}/{{ host_group }}
      when: proxy_is_set is not defined

    - name: generate assets
      command: bash -lc 'bundle exec rake RAILS_ENV=production assets:precompile RAILS_RELATIVE_URL_ROOT="/v1"' chdir=/home/{{rvm_user}}/{{ host_group }}

    # This blows away the DB, be careful with this...!
    #- name: load schema
    #  command: bash -lc 'rake RAILS_ENV=production db:schema:load' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: db migrate
      command: bash -lc 'bundle exec rake RAILS_ENV=production db:migrate' chdir=/home/{{rvm_user}}/{{ host_group }}

    - name: db seed
      command: bash -lc 'bundle exec rake RAILS_ENV=production db:seed' chdir=/home/{{rvm_user}}/{{ host_group }}

- hosts: dri_app
  user: root

  tasks:
#- template: src=../templates/resque.init dest=/etc/init.d/{{ host_group }} mode=0755
#- command: chkconfig --add {{ host_group }}
    - template: src=../templates/resque-worker.conf dest=/etc/init/resque-worker.conf mode=644
    - template: src=../templates/resque-workers.conf dest=/etc/init/resque-workers.conf mode=644
#- service: name=resque-workers enabled=yes state=started

    - name: Symlink hydra head
      file: src=/home/{{rvm_user}}/{{ host_group }}/public dest=/var/www/v1 state=link

    - name: Restart Apache
      service: name=apache2 state=restarted

    # house cleaning
    - file: path=/var/www/admin state=absent
    - file: path=/var/www/repository state=absent
