# order matters!
---
- hosts: all
  user: root
  accelerate: True
  roles:
    - { role: ../../roles/nagios-nrpe }

- hosts: monitoring
  user: root
  accelerate: True

  roles:
    - { role: ../../roles/nagios-server }
