# order matters!
---
- hosts: dri_app
  user: root

  tasks:
    - name: Drop in private ssh key from jenkins account
      copy: src=~/.ssh/id_rsa dest=~{{ rvm_user }}/.ssh/id_rsa owner={{rvm_user}} group={{rvm_user}} mode=0700

- include: setup-dri_app-nuig-rnag.yml
