# order matters!
---
- hosts: passenger;fedora;solr
  user: root
  ## dummy group just to pull in needed information for selfcontained runs

- hosts: dri_app
  user: $rvm_user

  tasks:
    - git: repo=ssh://git@lonsdale.tchpc.tcd.ie/navr/repository.dri.ie dest=~/repository.dri.ie update=yes
    - command: chdir='~/repository.dri.ie' bash -lc 'bundle'
    - command: chdir='~/repository.dri.ie' bash -lc 'rake generate'

- hosts: dri_app
  user: root

  tasks:
    - command: chdir='/home/{{rvm_user}}/repository.dri.ie' bash -lc 'rsync -a public/. /var/www/html/.'
    - file: path=/var/www/html/ state=directory owner=root group=root
