---
- hosts: all
  user: root

  tasks:
    - yum: name=libselinux-python state=present
      environment:
        http_proxy: http://{{proxy_server}}:{{proxy_port}}
        https_proxy: http://{{proxy_server}}:{{proxy_port}}
